name: Sync to Hugging Face hub

on:
  workflow_run:
    workflows: ["Weekly Build"]  # Debe coincidir con el nombre exacto del workflow
    types:
      - completed
  workflow_dispatch:  # Permite ejecución manual
  
jobs:
  sync-to-hub:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://jcval94chat:$HF_TOKEN@huggingface.co/spaces/jcval94chat/best-title main
