name: Sync to Hugging Face hub

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["weekly_build"] 
    types:
      - completed

jobs:
  sync-to-hub:
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || (github.event_name == 'workflow_dispatch') }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://<USERNAME>:${{ env.HF_TOKEN }}@huggingface.co/spaces/<USERNAME>/best-title main
